### ISSUE TITLE
Cannot charge my tesla roadster 

### ISSUE THREAD

**Issue by guigasthepro** [Boostvolt/tesla_ev#2]
Everytime i go to supercharger and click e to charge , it says its 100% then stop, but when i enter in the car the vehicle stays where it was

**Comment by Boostvolt** [comment]
You must use the roadster I have programmed. (https://github.com/Boostvolt/tesla_roadster) And install all necessary resources. tesla_ev, tesla_supercharger and tesla_redis.

**Comment by Boostvolt** [comment]
Does it work now? Are you using it locally or on a server? If it does not work, can you please send me a video?

**Comment by guigasthepro** [comment]
It was my fuel plugin that was restarting it to where it was, i already
fixed it but thank you
