### ISSUE TITLE
Unable to charge

### ISSUE THREAD

**Issue by venimo** [Boostvolt/tesla_ev#3]
When I'm driving my Tesla S to a charger point , it just doesn't show up. got tesla_ev and tesla_redis too

**Comment by Boostvolt** [comment]
Did you install tesla_supercharger (https://github.com/Boostvolt/tesla_supercharger)? And do you use tesla_models (https://github.com/Boostvolt/tesla_models)?

**Comment by Boostvolt** [comment]
Need to install https://github.com/Boostvolt/tesla_supercharger.
