### ISSUE TITLE
EV question

### ISSUE THREAD

**Issue by Skaphism** [Boostvolt/tesla_ev#4]
When i go to charge a vehicle it shows it charged to 100% but when i get in the vehicle it shows random percentage? are the teslas able to run completely out of battery?

**Comment by Boostvolt** [comment]
Which tesla model do you use exactly? And do you have all necessary resources installed on your server? Yes the tesla can drop to 0%, then the car can't drive anymore.

**Comment by Skaphism** [comment]
I am using all of the models mainly the modelX and model 3. I have the EV/Redis/Supercharger anything that was in the required dependencies i added to server

**Comment by Skaphism** [comment]
Found the issue. Had to blacklist the models in legacy fuel. Thanks for the info!
